import { WorkoutExercise } from '../Models/DbModels';

const exerciseData = [
  { name: 'bodyweight_squats', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bodyweight-squat-side.mp4', description: 'Bodyweight squats', gender_recommendation: { male: 90, female: 90 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'weighted_squats', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-goblet-squat-side.mp4',  description: 'Weighted squats', gender_recommendation: { male: 90, female: 90 }, requires_weight: true, weight_loss_recommended: 40, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'jumping_jacks', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-jump-squats-front.mp4', description: 'Cardio bodyweight exercise', gender_recommendation: { male: 80, female: 80 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 30, age_recommendation: { min: 12, max: 80 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'push_ups', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-push-up-side.mp4', description: 'Upper-body bodyweight strength exercise', gender_recommendation: { male: 85, female: 90 }, requires_weight: false, weight_loss_recommended: 65, muscle_growth_recommended: 80, age_recommendation: { min: 14, max: 80 }, focus_group: 'upper_body', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'dumbbell_rows', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-row-unilateral-side.mp4', description: 'Weighted back exercise with dumbbells', gender_recommendation: { male: 80, female: 75 }, requires_weight: true, weight_loss_recommended: 35, muscle_growth_recommended: 85, age_recommendation: { min: 16, max: 70 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'burpees', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-burpee-side.mp4', description: 'Full-body high-intensity bodyweight exercise', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 95, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 70 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'bodyweight_lunges', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-forward-lunges-front.mp4', description: 'Leg strength exercise using bodyweight for resistance', gender_recommendation: { male: 85, female: 90 }, requires_weight: false, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'weighted_lunges', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-single-arm-forward-lunge-side.mp4', description: 'Leg strength exercise using dumbbells for resistance', gender_recommendation: { male: 85, female: 90 }, requires_weight: true, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'plank', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-hand-plank-side_GnZ2NZh.mp4', description: 'Core stability bodyweight exercise', gender_recommendation: { male: 80, female: 85 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['abs', 'obliques', 'lower back'] },
  { name: 'mountain_climbers', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-mountain-climber-side.mp4', description: 'High-intensity cardio and core bodyweight movement', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 92, muscle_growth_recommended: 45, age_recommendation: { min: 14, max: 75 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'kettlebell_swings', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-swing-side.mp4', description: 'Explosive hip hinge movement with kettlebell', gender_recommendation: { male: 75, female: 80 }, requires_weight: true, weight_loss_recommended: 88, muscle_growth_recommended: 70, age_recommendation: { min: 18, max: 65 }, focus_group: 'posterior_chain', muscles: ['glutes', 'hamstrings', 'lower back'] },
  { name: 'bench_press', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-bench-press-side_KciuhbB.mp4', description: 'Chest and triceps strength exercise with barbell or dumbbells', gender_recommendation: { male: 85, female: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 90, age_recommendation: { min: 16, max: 70 }, focus_group: 'chest', muscles: ['chest', 'triceps', 'front delts'] },
  { name: 'deadlifts', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-deadlift-side.mp4', description: 'Full-body strength exercise using a barbell or dumbbells', gender_recommendation: { male: 90, female: 85 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 95, age_recommendation: { min: 16, max: 70 }, focus_group: 'posterior_chain', muscles: ['glutes', 'hamstrings', 'lower back'] },
  { name: 'overhead_press', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-seated-overhead-press-front.mp4', description: 'Shoulder strength exercise with barbell or dumbbells', gender_recommendation: { male: 80, female: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 85, age_recommendation: { min: 16, max: 70 }, focus_group: 'shoulders', muscles: ['delts', 'triceps', 'upper chest'] },
  { name: 'bicycle_crunches', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bicycle-crunch-side.mp4', description: 'Core exercise for abdominal strength and endurance', gender_recommendation: { male: 80, female: 85 }, requires_weight: false, weight_loss_recommended: 75, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 75 }, focus_group: 'core', muscles: ['abs', 'obliques'] },
  { name: 'jump_rope', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-jump-rope-side.mp4', description: 'Cardio conditioning exercise with a jump rope', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 95, muscle_growth_recommended: 25, age_recommendation: { min: 12, max: 75 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'wall_sit', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-wall-sit-side.mp4', description: 'Static quad endurance bodyweight exercise', gender_recommendation: { male: 80, female: 80 }, requires_weight: false, weight_loss_recommended: 45, muscle_growth_recommended: 50, age_recommendation: { min: 12, max: 75 }, focus_group: 'legs', muscles: ['quads', 'glutes'] },
  { name: 'step_ups', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-step-up-side.mp4', description: 'Leg power exercise using a bench or step', gender_recommendation: { male: 85, female: 90 }, requires_weight: true, weight_loss_recommended: 75, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'calves'] },
  { name: 'tricep_dips', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bench-dips-side.mp4', description: 'Bodyweight upper-body exercise for triceps and chest', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: false, weight_loss_recommended: 60, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['triceps', 'chest', 'shoulders'] },
  { name: 'high_knees', demonstration_url: 'https://i.pinimg.com/originals/a6/8c/6a/a68c6ac541ae8b403a4b34cda93441e3.gif', description: 'Bodyweight cardio sprinting motion to boost heart rate', gender_recommendation: { male: 85, female: 85, other: 85 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 35, age_recommendation: { min: 12, max: 70 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'glute_bridges', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-glute-bridge-side.mp4', description: 'Glute and hamstring bodyweight strength exercise', gender_recommendation: { male: 75, female: 90, other: 82 }, requires_weight: false, weight_loss_recommended: 55, muscle_growth_recommended: 65, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'side_plank', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-elbow-side-plank-front.mp4', description: 'Oblique core stability exercise', gender_recommendation: { male: 75, female: 85, other: 80 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 50, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['obliques', 'abs'] },
  { name: 'bodyweight_hip_thrusts', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bodyweight-heels-elevated-hip-thrust-side.mp4', description: 'Bodyweight glute bridge variation for hip strength', gender_recommendation: { male: 80, female: 90, other: 85 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 70, age_recommendation: { min: 16, max: 75 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'weighted_hip_thrusts', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-hip-thrust-front.mp4', description: 'Weighted glute bridge variation using dumbbells or a barbell', gender_recommendation: { male: 80, female: 90, other: 85 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 75 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'lat_pull_downs', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-machine-pulldown-side.mp4', description: 'Back strength exercise with cable or bands', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 40, muscle_growth_recommended: 85, age_recommendation: { min: 14, max: 75 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'tricep_extensions', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-skullcrusher-side_bgn7Uzz.mp4', description: 'Isolated triceps exercise with dumbbell or cable', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['triceps'] },
  { name: 'chair_squats', demonstration_url: 'https://www.strengthlog.com/wp-content/uploads/2020/06/Chair-Squats.gif', description: 'Bodyweight squat variation using a chair for support', gender_recommendation: { male: 45, female: 90, other: 67 }, requires_weight: false, weight_loss_recommended: 55, muscle_growth_recommended: 65, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'wall_push_ups', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-push-up-side.mp4', description: 'Upper-body push exercise using a wall for low-impact strength', gender_recommendation: { male: 45, female: 85, other: 65 }, requires_weight: false, weight_loss_recommended: 35, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'upper_body', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'resistance_band_rows', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Band-band-row-front.mp4', description: 'Back exercise using a resistance band anchored at home', gender_recommendation: { male: 75, female: 85, other: 80 }, requires_weight: true, weight_loss_recommended: 45, muscle_growth_recommended: 75, age_recommendation: { min: 12, max: 80 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'reverse_lunges', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-single-arm-reverse-lunge-side.mp4', description: 'Leg exercise stepping backward into a lunge for stability', gender_recommendation: { male: 45, female: 90, other: 67 }, requires_weight: true, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'seated_dumbbell_curls', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-seated-curl-side.mp4', description: 'Arm strength exercise sitting and curling dumbbells', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['biceps'] },
  { name: 'bird_dogs', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bird-dog-side.mp4', description: 'Low-impact core and back stability exercise on hands and knees', gender_recommendation: { male: 75, female: 80, other: 77 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['lower back', 'abs', 'glutes'] },
  { name: 'russian_twists', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-russian-twist-side.mp4', description: 'Core rotational exercise for obliques and abs', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 75 }, focus_group: 'core', muscles: ['obliques', 'abs'] },
  { name: 'bodyweight_calf_raises', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-calf-raises-side.mp4', description: 'Calf strengthening exercise using bodyweight only', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: false, weight_loss_recommended: 25, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['calves'] },
  { name: 'weighted_calf_raises', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-calf-raises-side.mp4', description: 'Calf strengthening exercise using dumbbells or other added weight', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['calves'] },
  { name: 'bodyweight_glute_kickbacks', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-kickbacks-side.mp4', description: 'Glute isolation movement using bodyweight only', gender_recommendation: { male: 75, female: 90, other: 82 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'band_pull_aparts', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Band-band-pull-apart-side.mp4', description: 'Upper-back and shoulder exercise using a resistance band', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 60, age_recommendation: { min: 12, max: 80 }, focus_group: 'shoulders', muscles: ['rear delts', 'upper back', 'traps'] },
  { name: 'seated_shoulder_press', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-seated-overhead-press-front.mp4', description: 'Shoulder exercise performed seated with dumbbells or cans', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 80, age_recommendation: { min: 14, max: 75 }, focus_group: 'shoulders', muscles: ['delts', 'triceps'] },
  { name: 'squat_thrusts', demonstration_url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-jump-squats-front.mp4', description: 'Full-body bodyweight movement with a quick squat to plank transition', gender_recommendation: { male: 85, female: 85, other: 85 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 50, age_recommendation: { min: 14, max: 75 }, focus_group: 'weight_loss', muscles: [] },
];

const seedExercises = async () => {
  const count = await WorkoutExercise.countDocuments();
  if (count > 0) return;

  await WorkoutExercise.insertMany(exerciseData);
  console.log(`Seeded ${exerciseData.length} exercises into the database.`);
};

export { seedExercises };
