import { WorkoutExercise } from '../Models/DbModels';

const exerciseData = [
  { name: 'bodyweight_squats', description: 'Bodyweight squats', gender_recommendation: { male: 90, female: 90 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'weighted_squats', description: 'Weighted squats', gender_recommendation: { male: 90, female: 90 }, requires_weight: true, weight_loss_recommended: 40, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'jumping_jacks', description: 'Cardio bodyweight exercise', gender_recommendation: { male: 80, female: 80 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 30, age_recommendation: { min: 12, max: 80 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'push_ups', description: 'Upper-body bodyweight strength exercise', gender_recommendation: { male: 85, female: 90 }, requires_weight: false, weight_loss_recommended: 65, muscle_growth_recommended: 80, age_recommendation: { min: 14, max: 80 }, focus_group: 'upper_body', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'dumbbell_rows', description: 'Weighted back exercise with dumbbells', gender_recommendation: { male: 80, female: 75 }, requires_weight: true, weight_loss_recommended: 35, muscle_growth_recommended: 85, age_recommendation: { min: 16, max: 70 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'burpees', description: 'Full-body high-intensity bodyweight exercise', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 95, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 70 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'bodyweight_lunges', description: 'Leg strength exercise using bodyweight for resistance', gender_recommendation: { male: 85, female: 90 }, requires_weight: false, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'weighted_lunges', description: 'Leg strength exercise using dumbbells for resistance', gender_recommendation: { male: 85, female: 90 }, requires_weight: true, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'plank', description: 'Core stability bodyweight exercise', gender_recommendation: { male: 80, female: 85 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['abs', 'obliques', 'lower back'] },
  { name: 'mountain_climbers', description: 'High-intensity cardio and core bodyweight movement', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 92, muscle_growth_recommended: 45, age_recommendation: { min: 14, max: 75 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'kettlebell_swings', description: 'Explosive hip hinge movement with kettlebell', gender_recommendation: { male: 75, female: 80 }, requires_weight: true, weight_loss_recommended: 88, muscle_growth_recommended: 70, age_recommendation: { min: 18, max: 65 }, focus_group: 'posterior_chain', muscles: ['glutes', 'hamstrings', 'lower back'] },
  { name: 'bench_press', description: 'Chest and triceps strength exercise with barbell or dumbbells', gender_recommendation: { male: 85, female: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 90, age_recommendation: { min: 16, max: 70 }, focus_group: 'chest', muscles: ['chest', 'triceps', 'front delts'] },
  { name: 'deadlifts', description: 'Full-body strength exercise using a barbell or dumbbells', gender_recommendation: { male: 90, female: 85 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 95, age_recommendation: { min: 16, max: 70 }, focus_group: 'posterior_chain', muscles: ['glutes', 'hamstrings', 'lower back'] },
  { name: 'overhead_press', description: 'Shoulder strength exercise with barbell or dumbbells', gender_recommendation: { male: 80, female: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 85, age_recommendation: { min: 16, max: 70 }, focus_group: 'shoulders', muscles: ['delts', 'triceps', 'upper chest'] },
  { name: 'bicycle_crunches', description: 'Core exercise for abdominal strength and endurance', gender_recommendation: { male: 80, female: 85 }, requires_weight: false, weight_loss_recommended: 75, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 75 }, focus_group: 'core', muscles: ['abs', 'obliques'] },
  { name: 'jump_rope', description: 'Cardio conditioning exercise with a jump rope', gender_recommendation: { male: 85, female: 85 }, requires_weight: false, weight_loss_recommended: 95, muscle_growth_recommended: 25, age_recommendation: { min: 12, max: 75 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'wall_sit', description: 'Static quad endurance bodyweight exercise', gender_recommendation: { male: 80, female: 80 }, requires_weight: false, weight_loss_recommended: 45, muscle_growth_recommended: 50, age_recommendation: { min: 12, max: 75 }, focus_group: 'legs', muscles: ['quads', 'glutes'] },
  { name: 'step_ups', description: 'Leg power exercise using a bench or step', gender_recommendation: { male: 85, female: 90 }, requires_weight: true, weight_loss_recommended: 75, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'calves'] },
  { name: 'tricep_dips', description: 'Bodyweight upper-body exercise for triceps and chest', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: false, weight_loss_recommended: 60, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['triceps', 'chest', 'shoulders'] },
  { name: 'high_knees', description: 'Bodyweight cardio sprinting motion to boost heart rate', gender_recommendation: { male: 85, female: 85, other: 85 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 35, age_recommendation: { min: 12, max: 70 }, focus_group: 'weight_loss', muscles: [] },
  { name: 'glute_bridges', description: 'Glute and hamstring bodyweight strength exercise', gender_recommendation: { male: 75, female: 90, other: 82 }, requires_weight: false, weight_loss_recommended: 55, muscle_growth_recommended: 65, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'side_plank', description: 'Oblique core stability exercise', gender_recommendation: { male: 75, female: 85, other: 80 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 50, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['obliques', 'abs'] },
  { name: 'bodyweight_hip_thrusts', description: 'Bodyweight glute bridge variation for hip strength', gender_recommendation: { male: 80, female: 90, other: 85 }, requires_weight: false, weight_loss_recommended: 50, muscle_growth_recommended: 70, age_recommendation: { min: 16, max: 75 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'weighted_hip_thrusts', description: 'Weighted glute bridge variation using dumbbells or a barbell', gender_recommendation: { male: 80, female: 90, other: 85 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 80, age_recommendation: { min: 16, max: 75 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'lat_pull_downs', description: 'Back strength exercise with cable or bands', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 40, muscle_growth_recommended: 85, age_recommendation: { min: 14, max: 75 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'tricep_extensions', description: 'Isolated triceps exercise with dumbbell or cable', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['triceps'] },
  { name: 'chair_squats', description: 'Bodyweight squat variation using a chair for support', gender_recommendation: { male: 45, female: 90, other: 67 }, requires_weight: false, weight_loss_recommended: 55, muscle_growth_recommended: 65, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'wall_push_ups', description: 'Upper-body push exercise using a wall for low-impact strength', gender_recommendation: { male: 45, female: 85, other: 65 }, requires_weight: false, weight_loss_recommended: 35, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'upper_body', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'resistance_band_rows', description: 'Back exercise using a resistance band anchored at home', gender_recommendation: { male: 75, female: 85, other: 80 }, requires_weight: true, weight_loss_recommended: 45, muscle_growth_recommended: 75, age_recommendation: { min: 12, max: 80 }, focus_group: 'back', muscles: ['lats', 'biceps', 'upper back'] },
  { name: 'reverse_lunges', description: 'Leg exercise stepping backward into a lunge for stability', gender_recommendation: { male: 45, female: 90, other: 67 }, requires_weight: true, weight_loss_recommended: 70, muscle_growth_recommended: 75, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['quads', 'glutes', 'hamstrings'] },
  { name: 'seated_dumbbell_curls', description: 'Arm strength exercise sitting and curling dumbbells', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 70, age_recommendation: { min: 14, max: 75 }, focus_group: 'upper_body', muscles: ['biceps'] },
  { name: 'bird_dogs', description: 'Low-impact core and back stability exercise on hands and knees', gender_recommendation: { male: 75, female: 80, other: 77 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 80 }, focus_group: 'core', muscles: ['lower back', 'abs', 'glutes'] },
  { name: 'russian_twists', description: 'Core rotational exercise for obliques and abs', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 55, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 75 }, focus_group: 'core', muscles: ['obliques', 'abs'] },
  { name: 'bodyweight_calf_raises', description: 'Calf strengthening exercise using bodyweight only', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: false, weight_loss_recommended: 25, muscle_growth_recommended: 45, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['calves'] },
  { name: 'weighted_calf_raises', description: 'Calf strengthening exercise using dumbbells or other added weight', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 30, muscle_growth_recommended: 55, age_recommendation: { min: 12, max: 80 }, focus_group: 'legs', muscles: ['calves'] },
  { name: 'bodyweight_glute_kickbacks', description: 'Glute isolation movement using bodyweight only', gender_recommendation: { male: 75, female: 90, other: 82 }, requires_weight: false, weight_loss_recommended: 40, muscle_growth_recommended: 60, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'weighted_glute_kickbacks', description: 'Glute isolation movement using ankle weights or dumbbells', gender_recommendation: { male: 75, female: 90, other: 82 }, requires_weight: true, weight_loss_recommended: 45, muscle_growth_recommended: 65, age_recommendation: { min: 14, max: 80 }, focus_group: 'legs', muscles: ['glutes', 'hamstrings'] },
  { name: 'band_pull_aparts', description: 'Upper-back and shoulder exercise using a resistance band', gender_recommendation: { male: 80, female: 80, other: 80 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 60, age_recommendation: { min: 12, max: 80 }, focus_group: 'shoulders', muscles: ['rear delts', 'upper back', 'traps'] },
  { name: 'seated_shoulder_press', description: 'Shoulder exercise performed seated with dumbbells or cans', gender_recommendation: { male: 80, female: 85, other: 82 }, requires_weight: true, weight_loss_recommended: 25, muscle_growth_recommended: 80, age_recommendation: { min: 14, max: 75 }, focus_group: 'shoulders', muscles: ['delts', 'triceps'] },
  { name: 'squat_thrusts', description: 'Full-body bodyweight movement with a quick squat to plank transition', gender_recommendation: { male: 85, female: 85, other: 85 }, requires_weight: false, weight_loss_recommended: 90, muscle_growth_recommended: 50, age_recommendation: { min: 14, max: 75 }, focus_group: 'weight_loss', muscles: [] },
];

const seedExercises = async () => {
  const count = await WorkoutExercise.countDocuments();
  if (count > 0) return;

  await WorkoutExercise.insertMany(exerciseData);
  console.log(`Seeded ${exerciseData.length} exercises into the database.`);
};

export { seedExercises };
